# PostgreSQL. Versions 9.3 and up are supported.
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: 1234

development:
  primary:
    <<: *default
    database: event_hub_development
  cache:
    <<: *default
    database: event_hub_cache_development
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: event_hub_queue_development
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: event_hub_cable_development
    migrations_paths: db/cable_migrate

test:
  <<: *default
  database: event_hub_test

production:
  primary:
    <<: *default
    database: event_hub_production
    username: event_hub
    password: <%= ENV["EVENT_HUB_DATABASE_PASSWORD"] %>
  cache:
    <<: *default
    database: event_hub_production_cache
    migrations_paths: db/cache_migrate
    username: event_hub
    password: <%= ENV["EVENT_HUB_DATABASE_PASSWORD"] %>
  queue:
    <<: *default
    database: event_hub_production_queue
    migrations_paths: db/queue_migrate
    username: event_hub
    password: <%= ENV["EVENT_HUB_DATABASE_PASSWORD"] %>
  cable:
    <<: *default
    database: event_hub_production_cable
    migrations_paths: db/cable_migrate
    username: event_hub
    password: <%= ENV["EVENT_HUB_DATABASE_PASSWORD"] %>
